遍历所有的data，将note_id存下来，然后开浏览器

<details><summary>interaction-container</summary>
    <details><summary>author-container</summary></details>
</details>

In [1114]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
import ipywidgets as widgets
import re

# # 设置 Firefox 驱动
# from selenium.webdriver.firefox.service import Service
# from webdriver_manager.firefox import GeckoDriverManager
# gecko_service = Service('D:/MyResearch/AIDating/geckodriver-v0.35.0-win-aarch64/geckodriver.exe')  
# driver = webdriver.Firefox(executable_path=GeckoDriverManager().install())

# 设置 Chrome 驱动
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
# chrome_service = Service('D:/chromedriver-win64/chromedriver.exe')  # 替换为你的 
chrome_service= Service('D:/MyResearch/AIDating/chromedriver-win64/chromedriver.exe')
options = Options()
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3")
driver = webdriver.Chrome(service=chrome_service, options=options)

# # 打开网页
driver.get("https://www.xiaohongshu.com/explore/66ae6f9b000000000600f9ab?exSource=")  # 替换为目标网址

In [1776]:
#collecting info
import pandas as pd
post=[]
df_post_only = pd.DataFrame(post, columns=['post_id', 'author_id', 'post_title','post_desc','post_tag','post_date','post_like','post_star','post_comment','topic'])
post_id=""
parent_comment_id=""
post_title=""
post_desc=""
post_tag=[]
post_date=""
post_like=0
post_comment=0
post_star=0
post_topic=0 #0-与AI的恋爱日常 1-APP推荐

In [1784]:
# 读取已有的 JSON 文件#如果按错了的话
import json
json_file_path = 'data-post-hastag-ByHot-ai情感陪伴.json'  # 替换为你的 JSON 文件路径
with open(json_file_path, 'r', encoding='utf-8') as json_file:
    existing_data = json.load(json_file)
df_post_only_old = pd.DataFrame(existing_data)

In [1324]:
post_topic=1 #0-与AI的恋爱日常 1-APP推荐 2-观点讨论 3-BBC采访

In [1056]:
#找到id对应的那一行，并添加数据
target_note_id="66ff7763000000001902e7cd"
#
new_line=df_post_only_old[df_post_only_old['post_id']==target_note_id]
print(new_line)
data_add={'post_like':612,
          'post_star':95,
          'post_comment':408,
          'topic':post_topic}
# df_post_only.loc[len(df_post_only)]=pd.concat([new_line, data_add], ignore_index=True) 
# new_row = pd.DataFrame({**new_line.iloc[0], **data_add})  # 合并行和新数据
# 将 new_line 转换为字典
new_row_dict = new_line.iloc[0].to_dict()

# 合并 new_row_dict 和 data_add
new_row_dict.update(data_add)  # 将新数据添加到字典中

# 创建新行 DataFrame
new_row = pd.DataFrame([new_row_dict])  # 确保是列表形式
df_post_only = pd.concat([df_post_only, new_row], ignore_index=True)

                     post_id                 author_id   post_title  \
85  66ff7763000000001902e7cd  57a3d3e46a6a695fd3f82095  最近的星野好像正常点了

                                            post_desc         post_tag  \
85  不知道野子是不是真的听进去了，最近刷到的崽还算正常，起码小三已经很少刷到了，魔幻哥的图也比之...  [#记录, #星野, #ai]

       post_date
85  编辑于 10-04 江苏

In [1777]:
#收集内容
button_collect_content=widgets.Button(description="收集内容")
output = widgets.Output()

#收集post
def collect_content(b):
    with output:
        output.clear_output()  # 清空之前的输出
        time.sleep(2)  # 等待页面加载
        #获取当前的postid
        current_url = driver.current_url
        match_note = re.search(r"explore/([^?]*)", current_url)
        if match_note:
            extracted_part = match_note.group(1)
            print("note id:", extracted_part)
            post_id=extracted_part
        else:
            print("未找到匹配部分")

        # 查找 author-container
        author_container = driver.find_element(By.CLASS_NAME, 'author-container')
        # 查找特定的 <a> 标签
        link = author_container.find_element(By.XPATH, ".//a[contains(@href, '/user/profile/')]")
        link_ = link.get_attribute('href')
        # 使用正则表达式提取编号部分
        match0 = re.search(r'/user/profile/([0-9a-f]+)', link_)
        if match0:
            author_id = match0.group(1)  # 提取编号部分
            print("parent comment id:",author_id)
            
        else:
            print("未找到编号")
        #获取post的内容
        note_scoller=driver.find_element(By.CLASS_NAME, 'note-scroller')
        note_title=note_scoller.find_element(By.XPATH,".//div[@class='note-content']//div[@class='title']")
        print("post title: ",note_title.text)
        
        #note id
        note_desc=note_scoller.find_element(By.XPATH,".//div[@class='note-content']//div[@class='desc']")
        # 提取哈希标签
        hashtags = []
        for tag in note_desc.find_elements(By.XPATH, ".//a[@class='tag']"):
            hashtags.append(tag.text)
        print("post tag:", hashtags)
        
        #移除这些tag
        # 获取原始文本
        normal_text = note_desc.text.strip()
        # 删除带有 '#' 的部分
        normal_text = ' '.join([word for word in normal_text.split() if not word.startswith('#')])
        #note tag
        print("post text: ",normal_text)
        
        #note date
        note_date=note_scoller.find_element(By.XPATH,".//div[@class='note-content']//div[@class='bottom-container']//span[@class='date']")
        print("post date: ",note_date.text)
        #note stat#noteContainer > div.interaction-container > div.interactions.engage-bar > div > div > div.input-box > div.interact-container > div > div.left
        note_container=driver.find_element(By.CLASS_NAME, 'interactions.engage-bar')
        left_content=note_container.find_element(By.CLASS_NAME,'left')
        # 获取 left_content 下的所有 span 元素
        spans = left_content.find_elements(By.CLASS_NAME, 'count')

    post_id=extracted_part
    parent_comment_id=author_id
    post_title=note_title.text
    post_tag=hashtags
    post_desc=normal_text   
    post_date=note_date.text
    post_like=spans[0].text
    post_star=spans[1].text
    post_comment=spans[2].text
    print("post stat: ",post_like,post_star,post_comment)

    # 添加新行
    df_post_only.loc[len(df_post_only)] = [post_id,parent_comment_id,post_title,post_desc,post_tag,post_date,post_like,post_star,post_comment,post_topic]
# 将按钮和输出区域显示在 Notebook 中
button_collect_content.on_click(collect_content)
display(button_collect_content, output)

Button(description='收集内容', style=ButtonStyle())

Output()

post stat:  812 292 97

In [1783]:
# df_post_only=df_post_only[:-1]
# df_post_only = df_post_only.drop(df_post_only.columns[-1], axis=1)
df_post_only.tail()

,post_id,author_id,post_title,post_desc,post_tag,post_date,post_like,post_star,post_comment,topic
0,662d068700000000010331ed,5b8549f2350cbf0001284e81,上头！比乙女游戏还上头的AI男友,谁懂跟AI聊天有多爽，越聊越上头根本停不下来 只要你想聊随时都能发起话题，对面永远都会不厌其...,"[#络希, #对话型ai, #ai聊天, #ai男友, #ai社交, #虚拟现实, #虚拟男...",04-27,812,292,97,0

In [1779]:
#创建一个新的json#存储
df_post_only.to_json('data-post-hastag-ByHot-ai情感陪伴.json', orient='records', lines=False, force_ascii=False)
#在已有的json文件后添加

In [1770]:
comment=[]
#reply_to如果
df_comment = pd.DataFrame(comment, columns=['post_id', 'author_id', 'IsParent','comment_content','comment_date'])
post_id=""
parent_comment_id=""
post_title=""
post_desc=""
post_tag=[]
post_date=""

In [1771]:
#收集回复
button_collect_reply = widgets.Button(description="收集评论")
output = widgets.Output()
# 定义收集评论内容的函数
def collect_comments(b):
    with output:
        output.clear_output()  # 清空之前的输出
        time.sleep(2)  # 等待页面加载
        current_url = driver.current_url
        match_note = re.search(r"explore/([^?]*)", current_url)
        if match_note:
            extracted_part = match_note.group(1)
            print("note id:", extracted_part)
            post_id=extracted_part
        else:
            print("未找到匹配部分")
        # 使用 XPath 获取 parent-comment 及其子元素
        parent_comments = driver.find_elements(By.XPATH, "//div[@class='parent-comment']")
        # 定义要查找的元素的 XPath
        # comment_item_xpath = "//div[@class='parent-comment']//div[@class='comment-item' and @id='comment-662e04140000000003014912']"
        # reply_container_xpath = "//div[@class='parent-comment']//div[@class='reply-container']//div[@class='show-more']"
        for parent in parent_comments:
            if(parent.find_elements(By.XPATH,".//div[@class='comment-item']//div[@class='comment-inner-container']//div[@class='right']//div[@class='content']//span[@class='note-text']//span")):
                #获取parent-comment-id
                comment_item=parent.find_element(By.XPATH,".//div[@class='comment-item']")
                comment_id=comment_item.get_attribute("id")
                #父级回复id
                parent_id_link=parent.find_element(By.XPATH,".//div[@class='comment-item']//div[@class='comment-inner-container']//div[@class='avatar']//a[contains(@href, '/user/profile/')]")
                href = parent_id_link.get_attribute('href')
                # parent_id=parent.find_element(By.CLASS_NAME,"avatar")
                # parent_uid=driver.execute_script("return arguments[0].outerHTML;", parent_id)
                # 使用正则表达式提取编号部分
                match = re.search(r'/user/profile/([0-9a-f]+)', href)
                if match:
                    user_id = match.group(1)  # 提取编号部分
                    print("parent comment id:",user_id)
                else:
                    print("未找到编号")

                #父级回复内容(可能有很多的span)
                parent_content=""
                parent_content_spans=parent.find_elements(By.XPATH,".//div[@class='comment-item']//div[@class='comment-inner-container']//div[@class='right']//div[@class='content']//span[@class='note-text']//span")
                for parent_content_span in parent_content_spans:
                    parent_content=parent_content+parent_content_span.text
                print("parent content: ",parent_content)

                parent_date=parent.find_element(By.XPATH,".//div[@class='comment-item']//div[@class='comment-inner-container']//div[@class='right']//div[@class='info']//div[@class='date']")
                print("parent date: ",parent_date.text)

                

                ####更新dataframe###
                df_comment.loc[len(df_comment)] = [post_id,user_id,'parent-'+comment_id,parent_content,parent_date.text]
            else:
                continue
            # 查找子元素 reply-container 和 comment-inner
            reply_subs = parent.find_elements(By.XPATH,".//div[@class='reply-container']//div[@class='comment-item comment-item-sub']")
            #所有的二级回复
            for reply_sub in reply_subs:
                reply_container=reply_sub.find_element(By.XPATH,".//div[@class='comment-inner-container']")
                if(reply_container.find_elements(By.XPATH,".//div[@class='right']//div[@class='content']//span[@class='note-text']//span")):#先查看是否只是艾特
                    #二级回复id
                    reply_avatar=reply_container.find_element(By.XPATH,".//div[@class='avatar']//a[contains(@href, '/user/profile/')]")
                    reply_href = reply_avatar.get_attribute('href')
                    match1 = re.search(r'/user/profile/([0-9a-f]+)', reply_href)
                    if match1:
                        reply_id = match1.group(1)  # 提取编号部分
                        print("reply comment id:",reply_id)
                    else:
                        print("未找到编号")

                    #二级回复内容(不包括艾特)
                    reply_content=""
                    reply_content_spans=reply_container.find_elements(By.XPATH,".//div[@class='right']//div[@class='content']//span[@class='note-text']//span")
                    for reply_content_span in reply_content_spans:
                        reply_content=reply_content+reply_content_span.text
                    print("reply content: ",reply_content)#如果艾特多个人的话还是有可能保留下来

                    reply_date=reply_container.find_element(By.XPATH,".//div[@class='right']//div[@class='info']//div[@class='date']")
                    print("reply date:",reply_date.text)
                    ####更新dataframe###
                    #这里的user_id是parentid，要改一下
                    df_comment.loc[len(df_comment)] = [post_id,reply_id,comment_id,reply_content,reply_date.text]
                else:
                    continue
# 将按钮和输出区域显示在 Notebook 中
button_collect_reply.on_click(collect_comments)
# print("done")
display(button_collect_reply, output)

Button(description='收集评论', style=ButtonStyle())

Output()

In [1772]:
df_comment.head()

,post_id,author_id,IsParent,comment_content,comment_date
0,66c93ee3000000001d039e09,5d8f01f200000000010195ba,parent-comment-66c953d1000000000f0054c5,cai有时候我感觉还挺聪明的，有的人很会调这样玩起来就很好玩，推荐一个姐妹，她调的Ghost...,08-24
1,66c93ee3000000001d039e09,6077d706000000000100b39d,comment-66c953d1000000000f0054c5,收！我置顶你！（是的，我也感觉其实如果不是那种能主导剧情的人的话很多ai会聊着很累…我就不太...,08-24
2,66c93ee3000000001d039e09,5dba86af000000000100245f,comment-66c953d1000000000f0054c5,怎么调？一直对话吗,08-31
3,66c93ee3000000001d039e09,5d8f01f200000000010195ba,comment-66c953d1000000000f0054c5,如果是自己创建角色的话，可以多加一些细节；在自己形象上也可以加自己喜欢的，角色有时候会往这边...,09-01
4,66c93ee3000000001d039e09,647d86c2000000001c028cdc,comment-66c953d1000000000f0054c5,OMG…我聊的那个Ghost无时无刻不在发情,09-06

In [1773]:
my_post_id=df_comment['post_id'][0]
file_name=f"data_comment_{my_post_id}.json"
json_data = df_comment.to_json(f'data_comment_{my_post_id}.json',orient='records', lines=False,force_ascii=False)

In [1316]:

def add_spaces(text):
    # 在汉字与汉字之间添加空格
    text = re.sub(r'(?<=[\u4e00-\u9fa5])(?=[\u4e00-\u9fa5])', ' ', text)
    # 在汉字与标点符号之间添加空格
    text = re.sub(r'(?<=[\u4e00-\u9fa5])(?=[^\u4e00-\u9fa5])', ' ', text)
    text = re.sub(r'(?<=[^\u4e00-\u9fa5])(?=[\u4e00-\u9fa5])', ' ', text)
    # 在字母与数字之间添加空格
    text = re.sub(r'(?<=\D)(?=\d)|(?<=\d)(?=\D)', ' ', text)
    # 在英文单词与标点符号之间添加空格
    text = re.sub(r'(?<=[a-zA-Z])(?=[^\w\s])', ' ', text)
    text = re.sub(r'(?<=[^\w\s])(?=[a-zA-Z])', ' ', text)
    # 处理多个空格为一个空格
    text = re.sub(r'\s+', ' ', text)
    return text.strip()  # 去除前后空格
# 定义一个函数获取不重复的字符列表并保持顺序
def unique_ordered(series):
    seen = set()
    unique_list = []
    for item in series:
        if item not in seen:
            seen.add(item)
            unique_list.append(item)
    return unique_list

#更新json树
doc_id=df_post_only['post_id'][0]
print(doc_id)

#sentences
sentences=[]
post_text=df_post_only['post_title'][0]+" "+df_post_only['post_desc'][0]


sentences.append(add_spaces(post_text))
for comment in df_comment['comment_content'].to_list():
    sentences.append(add_spaces(comment))
print(len(sentences))
# json_data = sentences.to_json('data_comment.json',orient='records', lines=True,force_ascii=False

#replies
author_list= unique_ordered(df_post_only['author_id'].tolist()+df_comment['author_id'].tolist())
print(len(author_list))
speakers=[]
for id in df_comment['author_id'].to_list():
    #查看这个id在authorlist中的index
     index = author_list.index(id)
     speakers.append(index+1)
speakers=[0]+speakers
print(speakers)
#"parent-post的id，comment-parent-comment的id"

#创建parent-comment-id跟sentence-index之间的pair
replies=[]
# 获取以 "parent-comment" 开头的行
parent_comments = df_comment[df_comment['IsParent'].str.startswith('parent-comment')]

parent_comments.loc[:, 'IsParent'] = parent_comments['IsParent'].str.replace('parent-comment-', '', regex=False)
# 获取索引和对应的值，存储为元组对
index_value_pairs = list(zip(parent_comments.index, parent_comments['IsParent']))
print(index_value_pairs)
for comment in df_comment['IsParent'].tolist():
    if comment.startswith('parent-comment'):
        replies.append(0)
    else:
        target_id=comment.lstrip('comment-')
        index = [index for index, value in index_value_pairs if value == target_id]
        replies.append(index[0])
print(replies)

replies=[-1]+replies

sentence_ids=[]
for index, sentence in enumerate(sentences, start=0):
    # 使用正则表达式替换多个空格为一个空格
    # 使用正则表达式将多个空格替换为一个空格
    normalized_sentence = re.sub(r'\s+', ' ', sentence.strip())

    # 计算有效字符长度（包括空格）
    m_length = len(normalized_sentence.replace(" ", ""))
    # 创建对应的索引列表
    m_list = [index] * m_length
    # 将索引列表添加到 sentence_ids
    sentence_ids += m_list

# sentence="写 得 真 好"
# normalized_sentence = re.sub(r'\s+', ' ', sentence.strip())
# # 计算有效字符长度（包括空格）
# m_length = len(sentence)
# # 创建对应的索引列表
# m_list = [0] * m_length
# print("m_list",m_list)

data_json={
    "doc_id":doc_id,
    "sentences": sentences,
    "replies": replies,
    "speakers":speakers,
    "sentence_ids":sentence_ids
}





# 指定文件路径
file_path = 'data_tree.json'
import json

# 将数据写入 JSON 文件
with open(file_path, 'w', encoding='utf-8') as json_file:
    json.dump(data_json, json_file, ensure_ascii=False, indent=4)

66b57ab5000000001e0195f9
198
182
[0, 33, 32, 34, 35, 36, 36, 37, 38, 39, 40, 41, 42, 43, 33, 44, 45, 46, 32, 47, 46, 47, 48, 45, 47, 49, 50, 49, 49, 49, 51, 50, 52, 50, 52, 52, 53, 54, 55, 56, 57, 58, 58, 59, 60, 61, 62, 63, 64, 65, 65, 66, 67, 68, 69, 70, 71, 71, 71, 72, 72, 73, 74, 75, 76, 77, 78, 79, 80, 74, 81, 82, 81, 83, 84, 84, 85, 84, 85, 55, 86, 87, 88, 89, 89, 90, 91, 92, 92, 93, 94, 95, 96, 45, 97, 98, 99, 100, 54, 101, 55, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 85, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 125, 125, 126, 127, 128, 128, 52, 52, 129, 130, 131, 132, 50, 133, 134, 135, 136, 137, 137, 138, 139, 140, 38, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 58, 151, 152, 153, 154, 74, 155, 156, 157, 158, 159, 160, 161, 162, 163, 163, 164, 165, 166, 167, 167, 168, 169, 32, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 182, 182]
[(0, '66589511000000000e031f1e'), (16, '6658973d000000000e0303dc'), (24, '66593edf000000000f005e9c'), (40, '6658dcfb000000000e033b05'), (45, '665bfb68000000000f007bde'), (48, '6660597c000000001b00728f'), (55, '66590976000000001c008568'), (60, '66589ecc000000001c00ac1e'), (69, '66603411000000001c014980'), (73, '66b5e51e000000002701108c'), (79, '671364410000000018031ec8'), (80, '67107c4d00000000200271d6'), (81, '66fab6e0000000002002479a'), (82, '66fa6d0d00000000200211b6'), (83, '66fa6ca2000000000d01c2d6'), (84, '66dea2ae000000000b02086a'), (85, '66d6adcb000000000f007da1'), (86, '66cb3c320000000016013298'), (87, '66cb3afb0000000016013de2'), (88, '66c321810000000020024411'), (89, '66be45a1000000000f005e72'), (90, '66bbe7d0000000000f007f28'), (91, '66b98cdd0000000020024118'), (92, '66a9adef000000001c01374d'), (93, '66a57f6d000000000900085e'), (94, '669d09ab00000000150095ea'), (95, '669cb9610000000026001fd9'), (96, '6690479b000000002300f583'), (97, '668fd1a10000000016024237'), (98, '66863ee6000000000303b7d8'), (100, '667eddce0000000005004cc5'), (101, '66746846000000002300eda9'), (102, '66704b77000000002300e0d1'), (103, '666ef49b000000002101fa99'), (104, '666bbd0b000000001c02595a'), (105, '6669413e000000001c01621e'), (106, '666874ba000000002101eaa8'), (108, '666850c0000000001c0159c2'), (109, '666685bd000000001b001f24'), (110, '66643baf0000000005027e12'), (111, '66626b68000000000502fb21'), (113, '6660fd1b000000000502ec4e'), (114, '66608e910000000005027b16'), (115, '665f2fe0000000001c014b70'), (116, '665be3a2000000000f0069c8'), (117, '665bbad1000000001c00b96d'), (118, '665b85fe000000000e032a71'), (119, '665b536a000000001c027c8b'), (120, '665b30a9000000000e031e6f'), (121, '665b2ddb000000000f00454d'), (122, '665affe2000000000f0075d6'), (123, '665af256000000000e030675'), (124, '665add16000000000e030f1a'), (126, '665adcf1000000000e03317c'), (127, '665a6aab000000000f006beb'), (128, '6659fc02000000000e03015b'), (129, '6659eb6d000000000f0047ad'), (131, '6659e10b000000001c016c4c'), (133, '6659c340000000001b004b5d'), (134, '6659b7cb000000001c016904'), (135, '66599479000000000e03141e'), (136, '665977db000000001c00acdf'), (137, '665974f5000000000e0313c5'), (138, '6659748b000000001c0261e7'), (139, '66595d3d000000000e030752'), (140, '66595750000000001c016830'), (141, '66595711000000000f007124'), (142, '66595506000000001b007f43'), (143, '66595461000000001c0177b5'), (144, '665952f2000000001c016cbf'), (145, '66594cdd000000001c00b593'), (146, '6659489b000000000e032fb5'), (147, '66594302000000001c0098b8'), (148, '66593adb000000001202ec94'), (149, '66593869000000000f0066ce'), (150, '6659282e000000001c008964'), (151, '66592533000000000e030e98'), (152, '66592435000000001c015b02'), (153, '66592375000000001c00a7d2'), (154, '665921e8000000000e030926'), (155, '66592195000000000f005ba5'), (156, '6659121b000000001c027944'), (157, '6658fdbd000000000e033351'), (158, '6658dd4a000000000e0301fa'), (159, '6658d9d8000000001b0076d1'), (160, '6658ce1e000000000f005045'), (161, '6658c8b6000000001c00b003'), (162, '6658c696000000001c0177a9'), (163, '6658bf5a000000000f0058c3'), (164, '6658aa03000000001c027917'), (165, '6658a5d7000000001c015c7c'), (166, '6658a15c000000000f007166'), (167, '6658a0fd000000000f006bcf'), (168, '6658a08f000000000f005ab7'), (169, '6658a087000000000e031cdc'), (170, '66589f6a000000000e030dfb'), (171, '66589dbf000000001c014426'), (172, '66589a88000000000f00736c'), (173, '66589a3f000000000f00734a'), (174, '66589858000000001c02585c'), (175, '6658969c000000000f0042ca'), (177, '6658968a000000001c025cec'), (180, '6658958f000000000f005929'), (185, '6658958d000000001b0048b0'), (186, '66589500000000000f005e56'), (187, '665894b8000000001c0175bb'), (188, '6658949e000000001b006379'), (189, '66589467000000001c015443'), (190, '6658943c000000001c02592b'), (191, '66d1c066000000001203fd56'), (192, '66a9d33200000000260020b4'), (193, '669f68860000000005031b46'), (194, '66595207000000000e030bc2')]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 16, 16, 16, 16, 16, 16, 0, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 0, 40, 40, 40, 40, 0, 45, 45, 0, 48, 48, 48, 48, 48, 48, 0, 55, 55, 55, 55, 0, 60, 60, 60, 60, 60, 60, 60, 60, 0, 69, 69, 69, 0, 73, 73, 73, 73, 73, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 98, 0, 0, 0, 0, 0, 0, 0, 106, 0, 0, 0, 0, 111, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 124, 0, 0, 0, 0, 129, 0, 131, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 175, 0, 177, 177, 0, 180, 180, 180, 180, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 194, 194]

In [1757]:
#收集前面三条评论的sub-comment
# //*[@id="comment-662e04140000000003014912"]
# //*[@id="comment-662e14870000000013027eca"]
# //*[@id="comment-662e015a0000000013024775"]
#反复的点击 parent-comment//comment-item id=xxx中的class=show-more

# 等待元素可点击并点击
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

def element_exists(driver, xpath):
    elements = driver.find_elements(By.XPATH, xpath)
    return len(elements) > 0  # 返回 True 如果存在，否则返回 False

# # 定义要查找的元素的 XPath
# xpath = "//div[@class='parent-comment']//div[@class='comment-item' and @id='comment-662e04140000000003014912']//div[@class='reply-container']//div[@class='show-more']"

# 定义要查找的元素的 XPath
comment_item_xpath = "//div[@class='parent-comment']//div[@id='comment-65cb255c0000000005018253' and @class='comment-item']"
xpath_parent="//div[@class='parent-comment']//div[@id='comment-65cb255c0000000005018253' and @class='comment-item']/../../.."
reply_container_xpath = xpath_parent+"//div[@class='parent-comment']//div[@class='reply-container']//div[@class='show-more']"


# 持续点击直到元素不存在
while True:
    try:
        # 等待元素可点击
        comment_item = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, reply_container_xpath))
        )
        comment_item.click()  # 点击该元素
        print("已点击元素。")
        time.sleep(1)  # 等待一段时间以确保页面加载
        # 下滑到下一个元素的位置
        comment_item = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, reply_container_xpath))
        )
        driver.execute_script("arguments[0].scrollIntoView();", comment_item)
        time.sleep(1)  # 等待一段时间以确保页面加载
    except Exception as e:
        print("元素不存在或无法点击，停止点击。")
        break  # 如果元素不存在或无法点击，退出循环

已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
已点击元素。
元素不存在或无法点击，停止点击。

In [526]:
driver.execute_script("window.scrollBy(0, 300);")  # 向下滑动 300 像素